"""Public API for vex_sim. Mirrors the VEX EXP Python surface.

The names exported here are the contract: student programs that work in
phase 1 must keep working through phase 6.
"""

from __future__ import annotations

from vex_sim.api._brain import Brain, Timer, Triport, sleep, wait
from vex_sim.api._controller import Controller
from vex_sim.api._drivetrain import DriveTrain, SmartDrive
from vex_sim.api._enums import (
    BRAKE,
    COAST,
    DEGREES,
    DPS,
    FORWARD,
    HOLD,
    IN,
    INCHES,
    LEFT,
    MM,
    MSEC,
    MV,
    PERCENT,
    PITCH,
    RAW,
    REVERSE,
    RIGHT,
    ROLL,
    RPM,
    SEC,
    SECONDS,
    TURNS,
    VOLT,
    XAXIS,
    YAW,
    YAXIS,
    ZAXIS,
    AxisType,
    BrakeType,
    Color,
    CurrentUnits,
    DirectionType,
    DistanceUnits,
    GearSetting,
    LEDStateType,
    ObjectSizeType,
    OrientationType,
    Ports,
    PowerUnits,
    RotationUnits,
    TemperatureUnits,
    TimeUnits,
    TorqueUnits,
    TurnType,
    VelocityUnits,
    VoltageUnits,
)
from vex_sim.api._motor import Motor, MotorGroup
from vex_sim.api._sensors import Bumper, Distance, Inertial, Optical

__all__ = [
    # Classes
    "Brain",
    "Bumper",
    "Controller",
    "Distance",
    "DriveTrain",
    "Inertial",
    "Motor",
    "MotorGroup",
    "Optical",
    "SmartDrive",
    "Timer",
    "Triport",
    # Top-level fns
    "wait",
    "sleep",
    # Enum classes
    "AxisType",
    "BrakeType",
    "Color",
    "CurrentUnits",
    "DirectionType",
    "DistanceUnits",
    "GearSetting",
    "LEDStateType",
    "ObjectSizeType",
    "OrientationType",
    "Ports",
    "PowerUnits",
    "RotationUnits",
    "TemperatureUnits",
    "TimeUnits",
    "TorqueUnits",
    "TurnType",
    "VelocityUnits",
    "VoltageUnits",
    # Bare-name unit/direction sentinels
    "BRAKE",
    "COAST",
    "DEGREES",
    "DPS",
    "FORWARD",
    "HOLD",
    "IN",
    "INCHES",
    "LEFT",
    "MM",
    "MSEC",
    "MV",
    "PERCENT",
    "PITCH",
    "RAW",
    "REVERSE",
    "RIGHT",
    "ROLL",
    "RPM",
    "SEC",
    "SECONDS",
    "TURNS",
    "VOLT",
    "XAXIS",
    "YAW",
    "YAXIS",
    "ZAXIS",
]
